spring:
  application:
    name: eureka-service

server:
  port: 8302

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
#zuul: 
#  prefix: /api
#  routes: 
   #itinerary-service: 
   #  path: /itinerary-service/**
   #  url: http://localhost:8300
#    consumer-service: 
#      path: /consumer-service/**
#      url: http://localhost:8301